-- Kreiranje tabele za slike ptica
CREATE TABLE ptice_slike (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  naziv_srpskom TEXT NOT NULL,
  naziv_latinskom TEXT NOT NULL,
  grupa INT NOT NULL,
  slike_vezbanje TEXT[] NOT NULL, -- Array naziva fajlova za vežbanje
  slike_test TEXT[] NOT NULL, -- Array naziva fajlova za test
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Dodavanje kolone tip_testa u tabelu rezultati_kviza
ALTER TABLE rezultati_kviza 
ADD COLUMN tip_testa TEXT DEFAULT 'oglasavanje'; -- 'oglasavanje' ili 'slike'

-- Politike pristupa za tabelu "ptice_slike"
-- Omogucava svima da citaju podatke iz tabele "ptice_slike"
CREATE POLICY "Public Read Access for ptice_slike"
ON ptice_slike
FOR SELECT
USING (true);

