-- Kreiranje tabele za ptice
CREATE TABLE ptice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  naziv_srpskom TEXT NOT NULL,
  naziv_latinskom TEXT NOT NULL UNIQUE,
  grupa INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kreiranje tabele za rezultate kviza
CREATE TABLE rezultati_kviza (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  broj_pitanja INT NOT NULL,
  rezultat JSONB NOT NULL, -- { "questions": [...], "userAnswers": [...], "score": 10 }
  poeni INT NOT NULL,
  user_email TEXT, -- Email korisnika koji je radio kviz
  zvanican_test BOOLEAN DEFAULT FALSE -- Da li je ovo zvanični test
);

-- Omogucavanje Realtime za tabele (opciono, ali korisno)
ALTER TABLE ptice REPLICA IDENTITY FULL;
ALTER TABLE rezultati_kviza REPLICA IDENTITY FULL;

-- Politike pristupa za tabelu "ptice"
-- Omogucava svima da citaju podatke iz tabele "ptice"
CREATE POLICY "Public Read Access for ptice"
ON ptice
FOR SELECT
USING (true);

-- Politike pristupa za tabelu "rezultati_kviza"
-- Omogucava samo autentifikovanim korisnicima da unose rezultate
CREATE POLICY "Authenticated users can insert quiz results"
ON rezultati_kviza
FOR INSERT
WITH CHECK (auth.role() = 'authenticated');
